#!/bin/bash

set -Eeux

source vars.sh

# TODO: Focal doesn't have a xserver HWE stack yet
XORG_HWE="${XORG_HWE:-}"

# HWE starts with y, Y or 1?
if [ "$HWE" = "yes" ]; then
    KERNEL_FLAVORS="generic-hwe-${BASEVERSION}"
    # XORG_HWE="xserver-xorg-hwe-${BASEVERSION}"
else
    KERNEL_FLAVORS="generic"
fi

lb config noauto \
    --architectures "$ARCH" \
    --mode ubuntu \
    --initramfs none \
    --distribution "$BASECODENAME" \
    --parent-distribution "$BASECODENAME" \
    --archive-areas "main restricted universe multiverse" \
    --parent-archive-areas "main restricted universe multiverse" \
    --linux-packages linux-image \
    --linux-flavours "$KERNEL_FLAVORS" \
    --bootappend-live "boot=casper maybe-ubiquity quiet splash" \
    --mirror-bootstrap "$MIRROR_URL" \
    --parent-mirror-bootstrap "$MIRROR_URL" \
    --parent-mirror-chroot "$MIRROR_URL" \
    --mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
    --parent-mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
    --mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
    --parent-mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
    --mirror-binary "mirror://mirrors.ubuntu.com/mirrors.txt" \
    --parent-mirror-binary "mirror://mirrors.ubuntu.com/mirrors.txt" \
    --keyring-packages ubuntu-keyring \
    --apt-options "--yes --option Acquire::Retries=5 --option Acquire::http::Timeout=100" \
    --cache-packages false \
    --cache-stages false \
    --binary-images iso-hybrid \
    --iso-application "$NAME" \
    --iso-volume "$NAME" \
    --initsystem systemd \
    --firmware-binary false \
    --firmware-chroot false \
    --syslinux-theme ubuntu \
    --zsync false \
    "${@}"

# replace channel and suite
sed -i "s/@CHANNEL/$CHANNEL/" config/archives/*.list*
sed -i "s/@BASECODENAME/$BASECODENAME/" config/archives/*.list*

DATE=$(date +%Y%m%d)
sed -i "s/@CHANNEL/$CHANNEL/" config/includes.binary/.disk/info
sed -i "s/@ARCH/$ARCH/" config/includes.binary/.disk/info
sed -i "s/@DISTRO_NAME/$NAME/" config/includes.binary/.disk/info
sed -i "s/@VERSION/$VERSION/" config/includes.binary/.disk/info
sed -i "s/@DATE/$DATE/" config/includes.binary/.disk/info

if [ ! "x${XORG_HWE}" == "x" ] ; then
  sed -i "s/#@XORG_HWE/$XORG_HWE/" config/package-lists/desktop.list.chroot_install
fi
