#!/bin/sh

set -e

. ./terraform.conf

if [ "$HWE_KERNEL" = "yes" ]; then
    KERNEL_FLAVORS="generic-hwe-${BASEVERSION}"
else
    KERNEL_FLAVORS="generic"
fi

if [ "$HWE_X11" = "yes" ]; then
    XORG_HWE="xserver-xorg-hwe-${BASEVERSION}"
fi

lb config noauto \
    --architectures "$ARCH" \
    --mode debian \
    --initramfs none \
    --distribution "$BASECODENAME" \
    --parent-distribution "$BASECODENAME" \
    --archive-areas "main restricted universe multiverse" \
    --parent-archive-areas "main restricted universe multiverse" \
    --linux-packages linux-image \
    --linux-flavours "$KERNEL_FLAVORS" \
    --bootappend-live "boot=casper only-ubiquity quiet splash" \
    --debootstrap-options="--extractor=ar --keyring=/etc/apt/trusted.gpg" \
    --checksums md5 \
    --mirror-bootstrap "$MIRROR_URL" \
    --parent-mirror-bootstrap "$MIRROR_URL" \
    --mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
    --parent-mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
    --mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
    --parent-mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
    --mirror-binary "http://archive.ubuntu.com/ubuntu/" \
    --parent-mirror-binary "http://archive.ubuntu.com/ubuntu/" \
    --keyring-packages ubuntu-keyring \
    --apt-options "--yes --option Acquire::Retries=2 --option Acquire::http::Timeout=45" \
    --cache-packages false \
    --uefi-secure-boot enable \
    --binary-images iso-hybrid \
    --iso-application "$NAME" \
    --iso-volume "$NAME" \
    --firmware-binary false \
    --firmware-chroot false \
    --zsync false \
    --security true \
    "${@}"

    # --mirror-chroot-security "https://security.debian.org/debian-security/" \
    # --parent-mirror-chroot-security "https://security.debian.org/debian-security/" \
    # --mirror-binary-security "https://security.debian.org/debian-security/" \
    # --parent-mirror-binary-security "https://security.debian.org/debian-security/" \
    # --mirror-binary "https://ftp.debian.org/debian/" \
    # --parent-mirror-binary "https://ftp.debian.org/debian/" \

# replace channel and suite
sed -i "s/@ARCH/$ARCH/" config/archives/*.list*
sed -i "s/@CHANNEL/$CHANNEL/" config/archives/*.list*
sed -i "s/@BASEDISTRO/$BASEDISTRO/" config/archives/*.list*
sed -i "s/@BASECODENAME/$BASECODENAME/" config/archives/*.list*

if [ "$CHANNEL" == "stable" ]; then
    sed -i "s/@COMPONENT/v$VERSION/" config/archives/*.list*
else
    sed -i "s/@COMPONENT/main/" config/archives/*.list*
fi

DATE=$(date +%Y%m%d)
sed -i "s/@CHANNEL/$CHANNEL/" config/includes.binary/.disk/info
sed -i "s/@CODENAME/$BASECODENAME/" config/includes.binary/.disk/info
sed -i "s/@ARCH/$ARCH/" config/includes.binary/.disk/info
sed -i "s/@DISTRO_NAME/$NAME/" config/includes.binary/.disk/info
sed -i "s/@VERSION/$VERSION/" config/includes.binary/.disk/info
sed -i "s/@DATE/$DATE/" config/includes.binary/.disk/info

sed -i "s/@XORG_HWE/$XORG_HWE/" config/package-lists/desktop.list.chroot_install
sed -i "s/@KERNEL_HEADERS/linux-headers-$KERNEL_FLAVORS/" config/package-lists/desktop.list.chroot_install
